skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
usdx_bridge = "9GFGtYxGtZg8Smk4yyya7zAT6V3WcLDsB9XWWQbxMS8"

[programs.devnet]
usdx_bridge = "9GFGtYxGtZg8Smk4yyya7zAT6V3WcLDsB9XWWQbxMS8"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
